experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    test_path: ../data/{0}/test.tsv
    validation_path: ../data/{0}/validation.tsv
  dataset: allrecipes
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.LightGCN:
      meta:
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        verbose: True
        save_recs: False
        validation_rate: 1
        validation_metric: Recall@20
      lr: [ loguniform, -9.210340372, -5.298317367 ]
      epochs: 200
      factors: 64
      batch_size: 256
      l_w: [ loguniform, -11.512925465, -2.30258509299 ]
      n_layers: 3
      seed: 123
      early_stopping:
        patience: 20
        mode: auto
        monitor: Recall@20
        verbose: True
    external.LightGCNP:
      meta:
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        verbose: True
        save_recs: False
        validation_rate: 1
        validation_metric: Recall@20
      lr: [ loguniform, -9.210340372, -5.298317367 ]
      epochs: 200
      factors: 64
      batch_size: 256
      a: [loguniform, -2.30258509299, -0.10536051565]
      b: [loguniform, -2.30258509299, -0.10536051565]
      l_w: [ loguniform, -11.512925465, -2.30258509299 ]
      n_layers: 3
      seed: 123
      early_stopping:
        patience: 20
        mode: auto
        monitor: Recall@20
        verbose: True
    external.GFCF:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        validation_metric: Recall@20
        restore: False
        save_recs: False
      svd_factors: [ 64, 128, 256, 512 ]
      alpha: [ 0.1, 0.3, 0.5, 0.7, 0.8 ]